### ISSUE TITLE
Conflicting names

### ISSUE THREAD

**Issue by iScienceLuvr** [matthewwardrop/python-parameters#1]
Hello,

I recently had an error with qubricks, as you know, as I downloaded the wrong parameters module. I feel that you should change the name of this module and update the dependencies for qubricks. The names for importing I recommend are:
- parampy
- parameter
- pyparam
- params - best as it seems this is the only name that doesn't conflict with other modules (I think..)
- python-parameters - also good for the above reason

**Comment by matthewwardrop** [comment]
Thanks for pointing this out. I was aware of the issue, but finally decided to do something about it. The next stable release of python-parameters will be parampy 2.0.0 . The changes in the git repository reflect this new name.
